# Configure.
language: python
python: 3.4
sudo: false

# Run.
install: pip install appveyor-artifacts coveralls tox
script: tox -e lint,py34,py33,pypy,py27
after_success:
  - mv .coverage .coverage.travis
  - appveyor-artifacts -mi download
  - coverage combine
  - coveralls
