# Configure.
language: python
matrix:
  include:
    - python: 3.5
      env: TOX_ENV=lint
      after_success:
        - echo
    - python: 3.5
      env: TOX_ENV=docs
    - python: 3.5
      env: TOX_ENV=py
sudo: false

# Run.
install: pip install tox
script: tox -e $TOX_ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)
