name: CI

on:
  pull_request:
  push:

jobs:

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        sphinx: [""]
        include:
          - os: macos-latest
            python: "3.10"
          - os: windows-latest
            python: "3.10"
          - os: ubuntu-latest
            python: "3.9"
            sphinx: "3.5.4"
          - os: ubuntu-latest
            python: "3.9"
            sphinx: "2.4.5"
          - os: ubuntu-latest
            python: "3.9"
            sphinx: "1.8.6"
          - os: ubuntu-latest
            python: "3.9"
            sphinx: "1.7.9"
    runs-on: "${{matrix.os}}"
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Initialize dependencies, id: init, uses: Robpol86/actions-init-deps-py@v3,
         with: {python-version: "${{matrix.python}}", postargs: " -E docs"}}
      - {name: Remove OpenGraph, run: "poetry remove sphinxext-opengraph; poetry remove -D $_", if: "startsWith(matrix.sphinx, '1.')"}
      - {name: Downgrade Sphinx, run: "poetry add --dev sphinx=${{matrix.sphinx}}", if: "${{matrix.sphinx}}"}
      - {name: Run lints, run: make lint}
      - {name: Run tests, run: make test, env: {PY_COLORS: 1}}
      - {name: Run integration tests, run: make it}
      - {name: Build docs, run: make docs, if: "!startsWith(matrix.sphinx, '1.')"}
      - {name: Build package, run: make build}
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with: {name: "coverage-${{runner.os}}-py${{steps.init.outputs.python-version}}"}
